# Generated by Django 3.2.8 on 2021-12-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('old', models.IntegerField()),
                ('friendry', models.IntegerField()),
            ],
        ),
    ]
