# Generated by Django 3.2.8 on 2021-12-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkapp', '0002_userlike_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='food',
            field=models.CharField(default='ハンバーグ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='music',
            field=models.CharField(default='Let it be', max_length=100),
            preserve_default=False,
        ),
    ]
